# Generated by Django 5.2.7 on 2025-10-13 16:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=200, verbose_name='Título')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='banners/images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])])),
                ('video', models.FileField(blank=True, null=True, upload_to='banners/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])])),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Ordem de exibição no carrossel (menor primeiro)', verbose_name='Ordem')),
                ('criado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['ordem', '-criado'],
            },
        ),
    ]
