# Generated by Django 5.2.7 on 2025-10-13 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mural', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='video',
        ),
    ]
